### ISSUE TITLE
Ensure coherence of .minf metadata and file-level metadata

### ISSUE THREAD

**Issue by denisri** [brainvisa/soma-io#1]
---

Author Name: **Leprince, Yann** (@ylep)
Original Redmine Issue: 13612, https://bioproj.extra.cea.fr/redmine/issues/13612
Original Date: 2015-10-21

---

When writing a data structure to a file, the metadata that are written to the @.minf@ side-car file can be incoherent with the metadata written in the file itself. This causes problems when files are read with applications that do not understand @.minf@ files.

For example, the voxel size stored in a NIfTI file can be out of sync with the voxel size stored in the .minf (see #13611 for details):
1. Using @pyaims@, set the @voxel_size@ to the Python list *@[0.5, 0.5, 0.5]@*
1. Reading the file back with its @.minf@ sidecar file gives the correct value @[ 0.5, 0.5, 0.5 ]@
1. Deleting the @.minf@ file (or reading the file in an application that does not understand @.minf@) gives an incorrect value: *@[ 1, 1, 1 ]@*

While this particular example is a bug in @somanifti@ (addressed in #13611), in my opinion the problem is deeper than this. The API around object headers (@GenericObject@ & co) is so liberal that it allows such incorrect usage (using a Python @list@ instead of @aims.vector_FLOAT@) to creep into the code, and remain undetected for a long time. While a general solution is likely difficult to find, maybe we could mitigate the problem:

1. some important attributes could be made “special”, i.e. having a fixed data type and run-time validation of the attribute value;
1. warnings could be emitted by the @Writer@ when a given attribute value cannot be represented in the file's metadata (e.g. Python @list@ instead of @std::vector<float>@);
1. we could read back the header using the corresponding @Reader@ just after writing a file (ignoring the @.minf@), and check that the extracted metadata is coherent.

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2015-10-22T13:46:39Z

---

If it was not for the bug #13612, this should work all well.
1. partly exists, but for reading: to ensure that some properties are read as specific types. It is not checked for writing, but should not be needed, normally...
2. this depends on specific formats, and the problem here is not that the value cannot be represented, but probably because it is misused (used as if it was a specific type when it is not always)
3. I think this should not be done systematically because there is a large overhead, but it should certainly be in a unit test somewhere, to test each file format IO.

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2015-10-22T16:41:45Z

---

Is the test enough to fix the issue ?

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Leprince, Yann** (@ylep)
Original Date: 2015-10-23T15:37:13Z

---

Awesome! This test should ensure consistency for the most fundamental metadata (and data!)

In order to test the consistency in more exotic, real-life conditions, maybe it would be useful to have a command-line tool that reads a file while ignoring its sidecar @.minf@, and prints any discrepancy between the header and the on-disk @.minf@? This would allow some manual testing, and it could also detect broken metadata in real use cases.

I am willing to write such a tool, but I am missing one piece of API: how can I read a file while ignoring its @.minf@ file?

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2015-10-23T17:05:40Z

---

??I am willing to write such a tool, but I am missing one piece of API: how can I read a file while ignoring its .minf file???

This API does not exist... up to now each format reader calls readMinf(), unconditionally. If we want to change that (maybe using a reader option) we have to change it in every reader. There is a bunch of them...

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2015-10-25T14:18:12Z

---

As long as it is only for testing, we could do this in another way:
* provide some data to the test function/program (file or in-memory data, if used as a function)
* write it (maybe as temporary)
* re-read it
* compare to initial header / meta-info
* remove the .minf file from the written data
* re-read it
* compare again

If it is to be used with actual "valuable" data, then the output would not be temporary, and we would have to write back the .minf file after testing.
This could be implemented either as a test program, or an option to AimsFileConvert, to convert and ensure that the converted file is consistent.

**Comment by sapetnioc** [comment]
I think we can close this one. If it is still necessary to have an option to read files without reading minf, a specific issue should be added.
