### ISSUE TITLE
Automatic storage of Nifti as Scaled S16 results in corrupted files

### ISSUE THREAD

**Issue by ylep** [brainvisa/soma-io#11]
On the current master branch, in some cases the automatic storage of `Volume`s as scaled S16 Nifti results in corrupted files, with values rounded to the nearest integer.

This bug is the cause of recent failures of highres-cortex tests (https://github.com/neurospin/highres-cortex/issues/11): the test pass when adding `options={"force_disk_data_type": True}` to the `aims.write` call.

I am still trying to find out exactly under which conditions the bug appears, but it seems to be related to volumes constructed from NumPy arrays.

**Comment by ylep** [comment]
Getting closer to the core issue: it must be related to incorrect accounting for array strides in https://github.com/brainvisa/soma-io/blob/8374cca39f4a3de619eec7daafc7f21763049c70/src/libsoma-io/io/scaledcoding.cc#L50-L54 because the issue disappears when the problematic NumPy array is reordered with `numpy.asfortranarray` before conversion to `aims.Volume`.

**Comment by ylep** [comment]
So I could pinpoint the issue to that code snippet, which does not properly iterate through the whole volume in case of a C-ordered NumPy array:

https://github.com/brainvisa/soma-io/blob/8374cca39f4a3de619eec7daafc7f21763049c70/src/libsoma-io/io/scaledcoding.cc#L79-L96

**Comment by denisri** [comment]
OK I see. I'll fix that soon. thanks for the debugging.

**Comment by ylep** [comment]
@denisri I'm on it, I think I just got it: it was due to incorrect usage of `line_NDIterator`.

**Comment by denisri** [comment]
Yes in the inner loop `++buf` should be replaced with `buf += strides[0]` or something like that.
There are probably other pieces of code not correctly taking strides into account...
