### ISSUE TITLE
volume:  segfault in VolumeRef copy constructor

### ISSUE THREAD

**Issue by denisri** [brainvisa/soma-io#3]
---

Author Name: **Souedet, Nicolas** (@nsouedet)
Original Redmine Issue: 15714, https://bioproj.extra.cea.fr/redmine/issues/15714
Original Date: 2016-11-14

---

Here is a simple example that was working a few days ago, but that generates segfault now:
```
//--- cartobase --------------------------------------------------------------
#include <cartobase/allocator/allocator.h>

//--- cartodata --------------------------------------------------------------
#include <cartodata/volume/volume.h>
//----------------------------------------------------------------------------

using namespace std;
using namespace carto;

int main(int argc, char** argv) {
  VolumeRef<float> fullVolume;
  fullVolume = Volume<float>(1, 1, 1, 1, AllocatorContext(), false);  
  
  return 0;
}

```

It seems to append during affectation in an implicit conversion. It goes through the all() method that converts a volume to a single boolean value but the volume is not allocated in this case, so it tries to access unallocated memory.

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Riviere, Denis** (@denisri)
Original Date: 2016-11-15T17:57:39Z

---

The VolumeRef = Volume conversion was not really expected, and not explicitely handled in operator =. The compiler seems to try to cast it to int (via bool), which will probably cause unexpected results.

**Comment by ylep** [comment]
Is this issue still relevant @nsouedet, or should we close it ?

**Comment by nsouedet** [comment]
Sorry to answer so late. I think that we can close this issue
